language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install bootstrap3
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

env:
  - DJANGO=1.9.1

before_install:
  - export PYTHONPATH=$HOME/builds/AShedko/kicktravel
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - python manage.py test --noinput
