# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171201_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Profile_groups',
        ),
    ]
